# Generated by Django 4.1.6 on 2023-02-28 10:52

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=200)),
                ('action_performed', models.CharField(max_length=200)),
                ('acted_by', models.CharField(default='Admin', max_length=200)),
                ('acted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHeight', models.FloatField(max_length=200, null=True)),
                ('Cview', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LItypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LItype', models.CharField(choices=[('Day', 'Day'), ('Mid-day', 'Mid-day'), ('Mid-Evening', 'Mid-Evening'), ('Night', 'Night')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vfms.company')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CameraNo', models.IntegerField(default=1)),
                ('CHeight', models.FloatField(null=True)),
                ('CView', models.CharField(max_length=20, null=True)),
                ('VideoStartTime', models.TimeField(null=True)),
                ('VideoEndTime', models.TimeField(null=True)),
                ('FileName', models.CharField(max_length=200, null=True)),
                ('VideoFile', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\drive'), upload_to='UploadedVideos/')),
                ('Remarks', models.CharField(max_length=1000, null=True)),
                ('RejectedReason', models.CharField(default='NA', max_length=1000, null=True)),
                ('videostatus', models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Modified', 'Modified')], default='New', max_length=10)),
                ('CModel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.cameramodel')),
                ('CompanyName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.company')),
                ('LICate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.litypes')),
                ('ProjectName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.project')),
                ('StationName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.location')),
                ('VideoFormat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vfms.videoff')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('loginID', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vfms.company')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vfms.role')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vfms.project'),
        ),
        migrations.CreateModel(
            name='ico1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Algorithm', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('Weight', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.company')),
                ('ProjectName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.project')),
                ('StationName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.location')),
                ('VideoFile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.videofiles')),
            ],
        ),
    ]
