# Generated by Django 4.1.6 on 2023-03-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0003_algo_icotest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icotest',
            name='Algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vfms.algo'),
        ),
    ]
