# Generated by Django 4.1.6 on 2023-03-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0004_alter_icotest_algorithm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ico1',
        ),
    ]
