# Generated by Django 4.1.6 on 2023-03-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0005_delete_ico1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ico1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Algorithm', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Weight', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.company')),
                ('ProjectName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.project')),
                ('StationName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.location')),
                ('VideoFile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.videofiles')),
            ],
        ),
    ]
