# Generated by Django 4.1.6 on 2023-03-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0007_remove_ico1_algorithm_remove_ico1_weight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='icotest',
        ),
    ]
