# Generated by Django 4.1.6 on 2023-03-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0009_icotest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icotest',
            name='Algorithm',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
