# Generated by Django 4.1.6 on 2023-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0010_alter_icotest_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='wei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.CharField(max_length=200)),
            ],
        ),
    ]
