# Generated by Django 4.1.6 on 2023-03-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0011_wei'),
    ]

    operations = [
        migrations.CreateModel(
            name='anotest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicles', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
