# Generated by Django 4.1.6 on 2023-03-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0014_vehicle_delete_anotest'),
    ]

    operations = [
        migrations.CreateModel(
            name='anof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagifyCustomListSuggestion', models.CharField(max_length=255)),
                ('vehi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.vehicle')),
            ],
        ),
    ]
