# Generated by Django 4.1.6 on 2023-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0015_anof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehi',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
