# Generated by Django 4.1.6 on 2023-03-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0018_rename_tagifycustomlistsuggestion_anof_tagify_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagify_options', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='anott',
        ),
        migrations.AddField(
            model_name='anof',
            name='tagify',
            field=models.ManyToManyField(blank=True, to='vfms.tag'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tagify',
            field=models.ManyToManyField(blank=True, to='vfms.tag'),
        ),
    ]
