# Generated by Django 4.1.6 on 2023-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0021_remove_anof_tagify_remove_vehicle_tagify_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anof',
            name='TagifyCustomListSuggestion',
        ),
        migrations.AddField(
            model_name='anof',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
