# Generated by Django 4.1.6 on 2023-03-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0022_remove_anof_tagifycustomlistsuggestion_anof_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anof',
            name='vehi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='vfms.vehicle'),
        ),
    ]
