# Generated by Django 4.1.6 on 2023-03-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0024_anott'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anof',
            name='vehi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vfms.vehicle'),
        ),
    ]
