# Generated by Django 4.1.6 on 2023-03-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0026_alter_anof_vehi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anof',
            name='vehi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.vehicle'),
        ),
    ]
