# Generated by Django 4.1.6 on 2023-03-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0027_alter_anof_vehi'),
    ]

    operations = [
        migrations.AddField(
            model_name='anott',
            name='op',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anott',
            name='vehi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.anof'),
        ),
    ]
