# Generated by Django 4.1.6 on 2023-03-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0029_rename_vehi_anott_vehic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anott',
            name='vehic',
        ),
        migrations.AddField(
            model_name='anott',
            name='vehi',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.vehicle'),
            preserve_default=False,
        ),
    ]
