# Generated by Django 4.1.6 on 2023-03-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0030_remove_anott_vehic_anott_vehi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anott',
            name='vehi',
        ),
    ]
