# Generated by Django 4.1.6 on 2023-03-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0031_remove_anott_vehi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anott',
            old_name='op',
            new_name='path',
        ),
        migrations.AddField(
            model_name='anott',
            name='seslect_vehicles',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.vehicle'),
            preserve_default=False,
        ),
    ]
