# Generated by Django 4.1.6 on 2023-03-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0032_rename_op_anott_path_anott_seslect_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anott',
            old_name='seslect_vehicles',
            new_name='selectvehicles',
        ),
        migrations.AddField(
            model_name='anott',
            name='tag',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.anof'),
            preserve_default=False,
        ),
    ]
