# Generated by Django 4.1.6 on 2023-03-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0033_rename_seslect_vehicles_anott_selectvehicles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anof',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='anott',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.anof', to_field='tags'),
        ),
    ]
