# Generated by Django 4.1.6 on 2023-03-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0034_alter_anof_tags_alter_anott_tag'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='anof',
            constraint=models.UniqueConstraint(fields=('tags',), name='unique_anof_tags'),
        ),
    ]
