# Generated by Django 4.1.6 on 2023-03-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0036_remove_anof_unique_anof_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anott',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.anof'),
        ),
    ]
