# Generated by Django 4.1.6 on 2023-03-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0037_alter_anott_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='proc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protype', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
