# Generated by Django 4.1.6 on 2023-03-09 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0038_proc'),
    ]

    operations = [
        migrations.AddField(
            model_name='anott',
            name='processtype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.proc'),
            preserve_default=False,
        ),
    ]
