# Generated by Django 4.1.6 on 2023-03-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0041_alter_anott_processtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anott',
            old_name='selectvehicles',
            new_name='class_names',
        ),
        migrations.RenameField(
            model_name='anott',
            old_name='path',
            new_name='input_folder_path',
        ),
        migrations.RenameField(
            model_name='anott',
            old_name='processtype',
            new_name='type_of_process',
        ),
    ]
