# Generated by Django 4.1.6 on 2023-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0042_rename_selectvehicles_anott_class_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icotest',
            name='Skipcount',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='anott',
            name='type_of_process',
            field=models.CharField(choices=[('add_id', 'Add ID'), ('rename', 'Rename'), ('crop_image', 'Crop'), ('remove_id', 'Remove ID')], max_length=10),
        ),
    ]
