# Generated by Django 4.1.6 on 2023-03-13 14:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0043_icotest_skipcount_alter_anott_type_of_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='icotest',
            name='VideoFile1',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\drive'), upload_to='UploadedVideos/'),
        ),
    ]
