# Generated by Django 4.1.6 on 2023-03-13 15:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0045_remove_icotest_videofile1'),
    ]

    operations = [
        migrations.AddField(
            model_name='icotest',
            name='VideoFile1',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\drive'), upload_to='UploadedVideos/'),
        ),
    ]
