# Generated by Django 4.1.6 on 2023-03-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0046_icotest_videofile1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icotest',
            name='VideoFile1',
        ),
    ]
