# Generated by Django 4.1.6 on 2023-03-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0047_remove_icotest_videofile1'),
    ]

    operations = [
        migrations.AddField(
            model_name='anott',
            name='TagifyCustomListSuggestion',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
