# Generated by Django 4.1.6 on 2023-03-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0048_anott_tagifycustomlistsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anott',
            name='class_names',
        ),
        migrations.AddField(
            model_name='anott',
            name='TagifyCustomInlineSuggestion',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
