# Generated by Django 4.1.6 on 2023-03-17 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0049_remove_anott_class_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anott',
            name='TagifyCustomInlineSuggestion',
        ),
        migrations.AddField(
            model_name='anott',
            name='class_names',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='vfms.vehicle'),
            preserve_default=False,
        ),
    ]
