# Generated by Django 4.1.6 on 2023-03-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0050_remove_anott_tagifycustominlinesuggestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anott',
            name='TagifyCustomListSuggestion',
        ),
    ]
