# Generated by Django 4.1.6 on 2023-03-18 05:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0051_remove_anott_tagifycustomlistsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='dups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_folder', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\drive'), upload_to='UploadedVideos/')),
                ('destination_folder', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\drive'), upload_to='UploadedVideos1/')),
            ],
        ),
    ]
