# Generated by Django 4.1.6 on 2023-03-18 06:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0052_dups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dups',
            name='destination_folder',
        ),
        migrations.RemoveField(
            model_name='dups',
            name='source_folder',
        ),
        migrations.AddField(
            model_name='dups',
            name='dropzone',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\drive'), upload_to='UploadedVideo/'),
        ),
    ]
