# Generated by Django 4.1.6 on 2023-03-18 09:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0057_alter_dups_dropzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dups',
            name='dropzone',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\drive'), upload_to='upload/'),
        ),
    ]
