# Generated by Django 4.1.6 on 2023-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0058_alter_dups_dropzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dups',
            name='dropzone',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
