# Generated by Django 4.1.6 on 2023-03-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0060_conv'),
    ]

    operations = [
        migrations.AddField(
            model_name='conv',
            name='txt_dir',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
