# Generated by Django 4.1.6 on 2023-03-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0061_conv_txt_dir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conv',
            old_name='txt_dir',
            new_name='root_dir',
        ),
        migrations.RemoveField(
            model_name='conv',
            name='xml_dir',
        ),
    ]
