# Generated by Django 4.1.6 on 2023-03-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0063_remove_dups_dropzone_dups_cropped_images_path_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dups',
            new_name='clus',
        ),
    ]
