# Generated by Django 4.1.6 on 2023-03-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0065_rename_cropped_images_path_clus_mov_dir_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conv',
            old_name='root_dir',
            new_name='myroot_dir',
        ),
    ]
