# Generated by Django 4.1.6 on 2023-03-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0067_conv_txt_dir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clus',
            old_name='root_dir',
            new_name='img_dir',
        ),
    ]
