# Generated by Django 4.1.6 on 2023-03-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0068_rename_root_dir_clus_img_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='clus',
            name='threshold',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
