# Generated by Django 4.1.6 on 2023-03-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0069_clus_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clus',
            name='threshold',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
