# Generated by Django 4.1.6 on 2023-03-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0070_alter_clus_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clus',
            name='threshold',
        ),
    ]
