# Generated by Django 4.1.6 on 2023-03-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0071_remove_clus_threshold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clus',
            old_name='img_dir',
            new_name='image_dir',
        ),
        migrations.RemoveField(
            model_name='clus',
            name='mov_dir',
        ),
    ]
